print("We're going to go on a journey")
food = input("What's your fav food?: ")
plant = input("Do you like any plants?: ")
cooking = input("What can you cook?: ")
print("You're going to go on a journey to explore the world.")
print("You're going to eat", food, "and plant", plant, "and" , cooking, ".")